[tool.black]
line-length = 80
extend-exclude = '''
/(
    # The following are specific to Black, you probably don't want those.
    tests/data/
    profiling/
    __pycache__/
)
'''
# unstable = true # Use this only if you want to use the latest, potentially unstable, formatting.
